// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechRadar.Data;

#nullable disable

namespace TechRadar.Data.Migrations
{
    [DbContext(typeof(TechRadarDbContext))]
    [Migration("20260303092120_SeedDataSources")]
    partial class SeedDataSources
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TechRadar.Core.Domain.AgentProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uuid");

                    b.Property<float?>("ConfidenceScore")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid?>("ExistingEntryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLlmEnriched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("ProposalType")
                        .HasColumnType("integer");

                    b.Property<string>("ProposedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("RecommendedQuadrant")
                        .HasColumnType("integer");

                    b.Property<int?>("RecommendedRing")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ResultingEntryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ReviewerNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("SourceReferences")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentRunId");

                    b.HasIndex("ExistingEntryId");

                    b.HasIndex("ResultingEntryId");

                    b.HasIndex("Status", "DetectedAt");

                    b.ToTable("agent_proposals", (string)null);
                });

            modelBuilder.Entity("TechRadar.Core.Domain.AgentRunLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Errors")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<int>("ProposalsDropped")
                        .HasColumnType("integer");

                    b.Property<int>("ProposalsGenerated")
                        .HasColumnType("integer");

                    b.Property<int>("SignalsFound")
                        .HasColumnType("integer");

                    b.Property<int>("SourcesScanned")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt")
                        .IsDescending();

                    b.HasIndex("Status");

                    b.ToTable("agent_run_logs", (string)null);
                });

            modelBuilder.Entity("TechRadar.Core.Domain.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LastSuccessfulScanAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("data_sources", (string)null);
                });

            modelBuilder.Entity("TechRadar.Core.Domain.RadarSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Entries")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("TriggerEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("TriggerEvent")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAt")
                        .IsDescending();

                    b.ToTable("radar_snapshots", (string)null);
                });

            modelBuilder.Entity("TechRadar.Core.Domain.RingChangeHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NewQuadrant")
                        .HasColumnType("integer");

                    b.Property<int>("NewRing")
                        .HasColumnType("integer");

                    b.Property<int?>("PreviousQuadrant")
                        .HasColumnType("integer");

                    b.Property<int?>("PreviousRing")
                        .HasColumnType("integer");

                    b.Property<Guid>("TechnologyEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TechnologyEntryId", "ChangedAt");

                    b.ToTable("ring_change_histories", (string)null);
                });

            modelBuilder.Entity("TechRadar.Core.Domain.TechnologyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedFromProposalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Quadrant")
                        .HasColumnType("integer");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Ring")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Quadrant", "Status");

                    b.HasIndex("Ring", "Status");

                    b.ToTable("technology_entries", (string)null);
                });

            modelBuilder.Entity("TechRadar.Core.Domain.AgentProposal", b =>
                {
                    b.HasOne("TechRadar.Core.Domain.AgentRunLog", "AgentRun")
                        .WithMany("Proposals")
                        .HasForeignKey("AgentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechRadar.Core.Domain.TechnologyEntry", "ExistingEntry")
                        .WithMany()
                        .HasForeignKey("ExistingEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TechRadar.Core.Domain.TechnologyEntry", "ResultingEntry")
                        .WithMany()
                        .HasForeignKey("ResultingEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AgentRun");

                    b.Navigation("ExistingEntry");

                    b.Navigation("ResultingEntry");
                });

            modelBuilder.Entity("TechRadar.Core.Domain.RingChangeHistory", b =>
                {
                    b.HasOne("TechRadar.Core.Domain.TechnologyEntry", "Entry")
                        .WithMany("RingHistory")
                        .HasForeignKey("TechnologyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("TechRadar.Core.Domain.AgentRunLog", b =>
                {
                    b.Navigation("Proposals");
                });

            modelBuilder.Entity("TechRadar.Core.Domain.TechnologyEntry", b =>
                {
                    b.Navigation("RingHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
